import {useState} from 'react';
import {Phone,Pencil,Plus,X,MapPin} from 'lucide-react';
import {Data} from './data';
import {CityContact,emptyCityContact,groupedCityContacts,repairContactDirectory,updateCityContact} from './cityContacts';
export default function ContactDirectory({data,disabled,onSave}:{data:Data,disabled:boolean,onSave:(data:Data)=>Promise<boolean>}){
 const [draft,setDraft]=useState<CityContact|null>(null),[original,setOriginal]=useState<CityContact|undefined>(),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const contacts=groupedCityContacts(data).flatMap(g=>g.contacts).sort((a,b)=>(a.company||'').localeCompare(b.company||'','es')||a.city.localeCompare(b.city,'es')||a.name.localeCompare(b.name,'es'));
 function edit(c?:CityContact){setOriginal(c?{...c}:undefined);setDraft(c?{...c}:{id:'',city:'',...emptyCityContact});setError('');}
 async function submit(e:React.FormEvent){e.preventDefault();if(!draft||saving)return;if(!draft.company?.trim()||!draft.city.trim()){setError('Indica la empresa y la ciudad.');return;}if(!draft.name.trim()&&!draft.phone.trim()&&!draft.address.trim()){setError('Agrega el lugar, teléfono o dirección.');return;}setSaving(true);try{const next=repairContactDirectory(structuredClone(data));updateCityContact(next,original,draft.city,{...draft,company:draft.company});if(await onSave(next))setDraft(null);else setError('No se pudo guardar. Tus cambios siguen en el formulario.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setSaving(false);}}
 return <><section className="contact-list">{contacts.map(c=><article className="service city-card" key={c.id}><div className="service-top"><div><p className="card-label">EMPRESA</p><h3 className="contact-company-name">{c.company||'Empresa por asignar'}</h3></div><button className="icon" disabled={disabled} aria-label={'Editar '+c.company+' en '+c.city} onClick={()=>edit(c)}><Pencil size={18}/></button></div><p className="card-label">CIUDAD</p><p className="contact-city-name">{c.city}</p><p className="card-label">LUGAR</p><b>{c.name||'Lugar por confirmar'}</b>{c.address&&<p><MapPin size={15}/> {c.address}</p>}<div className="contacts">{c.phone?<a href={'tel:'+c.phone.replace(/[^+\d]/g,'')}><Phone size={16}/>{c.phone}</a>:<span className="muted">Sin teléfono registrado</span>}</div></article>)}{!contacts.length&&<div className="blank"><Phone size={32}/><h2>Aún no hay contactos</h2><p>Agrega el contacto de una empresa y su ciudad.</p></div>}<button className="secondary add-city-contact" disabled={disabled} onClick={()=>edit()}><Plus size={18}/>Agregar contacto</button></section><p className="muted" style={{fontSize:11,marginTop:12}}>Contactos · versión 2.1</p>{draft&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="contact-title"><div className="modal-head"><h2 id="contact-title">{original?'Editar contacto':'Agregar contacto'}</h2><button className="icon" disabled={saving} aria-label="Cerrar" onClick={()=>setDraft(null)}><X/></button></div><form onSubmit={submit}>{error&&<p className="error" role="alert">{error}</p>}<label>Empresa<input autoFocus required maxLength={100} value={draft.company||''} onChange={e=>setDraft({...draft,company:e.target.value})}/></label><label>Ciudad<input required maxLength={100} value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></label><label>Lugar<input maxLength={200} placeholder="Taquilla, terminal, paradero…" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Teléfono<input type="tel" maxLength={50} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Dirección o ubicación<input maxLength={300} value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><div className="form-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>setDraft(null)}>Cancelar</button><button className="primary" disabled={saving||disabled}>{saving?'Guardando…':'Guardar contacto'}</button></div></form></section></div>}</>;
}
