import{dataSchema,Data}from'./data';import{readNotebook,finishSync,mergeData}from'./storage';
const scope='https://www.googleapis.com/auth/drive.appdata';const prefix='mis-rutas-snapshot-';let token='',expires=0,clientId='',running=false;let account='';
export async function setupDrive(){const r=await fetch('./config.json');if(!r.ok)throw Error('No se pudo cargar la configuración.');const config=await r.json();clientId=config.googleClientId||'';return!!clientId;}
export function connected(){return!!token&&Date.now()<expires;}
export function connectDrive():Promise<void>{return new Promise((resolve,reject)=>{
 if(!clientId){reject(Error('La conexión con Google Drive está pendiente de configuración. Tus datos siguen guardados en este dispositivo.'));return;}
 const google=(window as any).google;if(!google?.accounts?.oauth2){reject(Error('No se pudo cargar Google. Revisa tu conexión y vuelve a intentar.'));return;}
 const client=google.accounts.oauth2.initTokenClient({client_id:clientId,scope,callback:(response:any)=>{if(response.error){reject(Error('No se concedió acceso a Google Drive.'));return;}token=response.access_token;expires=Date.now()+Number(response.expires_in)*1000-60000;resolve();},error_callback:()=>reject(Error('Se canceló la conexión con Google Drive.'))});client.requestAccessToken({prompt:'select_account'});
});}
export function disconnectDrive(){token='';expires=0;account='';}
async function api(url:string,init:RequestInit={}){if(!connected())throw Error('Pulsa Conectar Drive para renovar el acceso.');const r=await fetch(url,{...init,headers:{...Object.fromEntries(new Headers(init.headers).entries()),Authorization:'Bearer '+token}});if(!r.ok){if(r.status===401){disconnectDrive();throw Error('El acceso a Drive venció. Conecta de nuevo; tus cambios siguen guardados.');}throw Error('Drive no pudo completar la operación ('+r.status+'). Tus cambios siguen guardados en el dispositivo.');}return r;}
async function identity(){const r=await api('https://www.googleapis.com/drive/v3/about?fields=user(permissionId,emailAddress)');const j=await r.json();return j.user?.permissionId||j.user?.emailAddress;}
export async function listBackups(){let page='';const files:any[]=[];do{const params=new URLSearchParams({spaces:'appDataFolder',q:"name contains '"+prefix+"'",fields:'nextPageToken,files(id,name,modifiedTime)',orderBy:'modifiedTime desc',pageSize:'100',...(page?{pageToken:page}:{})});const r=await api('https://www.googleapis.com/drive/v3/files?'+params);const j=await r.json();files.push(...j.files);page=j.nextPageToken||'';}while(page);return files.filter(f=>f.name.startsWith(prefix));}
export async function readBackup(id:string):Promise<Data>{const r=await api('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?alt=media');const j=await r.json();if(j.format!=='mis-rutas'||j.version!==1)throw Error('La copia no es compatible.');return dataSchema.parse(j.data);}
function deviceId(){let id=localStorage.getItem('mis-rutas-device');if(!id){id=crypto.randomUUID();localStorage.setItem('mis-rutas-device',id);}return id;}
async function upload(data:Data){const boundary='routes_'+crypto.randomUUID();const content=JSON.stringify({format:'mis-rutas',version:1,savedAt:new Date().toISOString(),data});const body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify({name:prefix+deviceId()+'-'+Date.now()+'.json',parents:['appDataFolder']})+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+content+'\r\n--'+boundary+'--';const response=await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});return(await response.json()).id as string;}
export async function synchronize(){if(running)throw Error('La sincronización ya está en curso.');running=true;try{const current=await readNotebook();account=await identity();if(!account)throw Error('No se pudo identificar la cuenta de Drive.');if(current.account&&current.account!==account)throw Error('Esta libreta está vinculada a otra cuenta de Google. Conecta la misma cuenta para recuperar sus copias.');const files=await listBackups();const latest=new Map<string,any>();for(const file of files){const device=file.name.slice(prefix.length,prefix.length+36);if(!latest.has(device))latest.set(device,file);}let merged=current.data;for(const file of latest.values()){if(current.seen?.includes(file.id))continue;const remote=await readBackup(file.id);merged=mergeData(merged,remote,current.base);}if(current.dirty||!files.length||JSON.stringify(merged)!==JSON.stringify(current.base)){const id=await upload(merged);files.push({id});}return await finishSync(current.revision,merged,account,[...new Set([...(current.seen||[]),...files.map(f=>f.id)])]);}finally{running=false;}}
